- name: Install cryptsetup
  ansible.builtin.package:
    name: cryptsetup
    state: present

- name: Generate host passphrase
  ansible.builtin.shell: openssl rand -base64 16 > /root/.encrypted_passphrase 
  args: 
    creates: /root/.encrypted_passphrase
  no_log: true

- name: Set permission to passphrase
  ansible.builtin.file:
    path: /root/.encrypted_passphrase
    owner: root
    group: root
    mode: '0400'

- name: Fetching host part passphrase
  ansible.builtin.slurp:
    src: /root/.encrypted_passphrase
  register: encrypted_passphrase_host
  no_log: true

- name: Create LUKS container with a combined passphrase
  community.crypto.luks_device:
    device: "{{ item.device }}"
    passphrase: "{{ item.pass }}"
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    state: "opened"
  # no_log: true
  loop:
    - { name: "encrypted_disk", type: "luks2", device: "{{ encrypted_disk }}", pass: "{{ encrypted_disk_key }}{{ encrypted_passphrase_host['content'] | b64decode }}"}
    - { name: "encrypted_partition", type: "luks1", device: "{{ encrypted_partition }}", pass: "{{ encrypted_partition_key }}{{ encrypted_passphrase_host['content'] | b64decode }}"}
  ignore_errors: true
  register: create_luks_status


- name: Create filesystem on the encrypted disk
  community.general.filesystem:
    fstype: ext4
    dev: "/dev/mapper/{{ item }}"
  loop:
    - encrypted_disk
    - encrypted_partition
  ignore_errors: true

- name: Mount the encrypted disk
  ansible.posix.mount:
    path: "{{ item.mount }}"
    src: "/dev/mapper/{{ item.name }}"
    fstype: ext4
    state: ephemeral
  register: status_encrypted_disks
  loop:
    - { name: "encrypted_disk", mount: "{{ encrypted_disk_mount }}", status: "status_encrypted_disk"}
    - { name: "encrypted_partition", mount: "{{ encrypted_partition_mount }}", status: "status_encrypted_partition"}
  ignore_errors: true

- name: Check luks partitions
  ansible.builtin.shell: lsblk | grep -i crypt
  register: luks_partitions

- name: Display encrypted mounts details
  ansible.builtin.debug:
    msg: "{{ status_encrypted_disks }}"
