# encrypted/tasks/encrypt_disks.yml
- name: Install cryptsetup
  ansible.builtin.package:
    name: cryptsetup
    state: present

- name: Generate host passphrase
  ansible.builtin.shell: openssl rand -base64 16 > /root/.encrypted_passphrase 
  args: 
    creates: /root/.encrypted_passphrase
  no_log: true

- name: Set permission to passphrase
  ansible.builtin.file:
    path: /root/.encrypted_passphrase
    owner: root
    group: root
    mode: '0400'

- name: Fetching host part passphrase
  ansible.builtin.slurp:
    src: /root/.encrypted_passphrase
  register: encrypted_passphrase_host
  no_log: true

- name: Create LUKS container with a combined passphrase
  community.crypto.luks_device:
    device: "{{ item.device }}"
    passphrase: "{{ item.pass }}"
    name: "{{ item.name }}"
    state: "opened"
  no_log: true
  loop:
    - { name: "encrypted_disk", device: "{{ encrypted_disk }}", pass: "{{ encrypted_disk_key }}{{ encrypted_passphrase_host['content'] | b64decode }}"}
    - { name: "encrypted_partition", device: "{{ encrypted_partition }}", pass: "{{ encrypted_partition_key }}{{ encrypted_passphrase_host['content'] | b64decode }}"}

- name: Create filesystem on the encrypted disk
  community.general.filesystem:
    fstype: ext4
    dev: "/dev/mapper/{{ item }}"
  loop:
    - encrypted_disk
    - encrypted_partition

- name: Mount the encrypted disk
  ansible.builtin.mount:
    path: "{{ item.mount }}"
    src: "/dev/mapper/{{ item.name }}"
    fstype: ext4
    state: ephemeral
  register: status_encrypted_disks
  loop:
    - { name: "encrypted_disk", mount: "{{ encrypted_disk_mount }}", status: "status_encrypted_disk"}
    - { name: "encrypted_partition", mount: "{{ encrypted_partition_mount }}", status: "status_encrypted_partition"}

- name: Check luks partitions
  ansible.builtin.shell: blkid -t TYPE=crypto_LUKS | grep "/dev/sdb\|/dev/loop10"
  register: luks_partitions

- name: Display encrypted mounts details
  ansible.builtin.debug:
    msg: "{{ status_encrypted_disks }}"
