# defaults/main.yml
encrypted_disk: "/dev/sdb"           # disk to be encrypted
key_encrypted_disk: "oxK0CdENG1PgAZfAgEMSBw==" # it shouldnt be here 
encrypted_partition: "/dev/loop10"       # Partition next to root to be encrypted
key_encrypted_partition: "oxK0CdENG1PgAZfAgEMSBw=="  # it shouldnt be here
mount_point_disk: "/mnt/encrypted_disk"    # Mount point for encrypted partition
mount_point_partition: "/mnt/encrypted_partition"    # Mount point for encrypted partition
cpu_governor: "performance"           # Desired CPU governor (e.g., performance)
new_interface_name: "net0"            # New interface name
interface_name: "{{ hostvars[inventory_hostname].ansible_default_ipv4.interface }}"
inteface_mac_addr: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
