# encrypted_disk: "xvdf"           # disk to be encrypted
# encrypted_disk_key: "oxK0CdENG1PgAZfAgEMSBw==" # it shouldnt be here part of passphrase for luks disk encryption
# encrypted_disk_mount: "xvda14"    # Mount point for encrypted partition
# encrypted_partition: "/dev/loop10"       # Partition next to root to be encrypted
# encrypted_partition_key: "oxK0CdENG1PgAZfAgEMSBw=="  # it shouldnt be here part of passphrase for luks partition encryption
# encrypted_partition_mount: "/mnt/encrypted_partition"    # Mount point for encrypted partition
