# tasks/set_cpu.yml
- name: Disable cstate in grub default
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX=$GRUB_CMDLINE_LINUX" processor.max_cstate=1 intel_idle.max_cstate=0"'
    state: present
  register: cstate_result
  notify:
    - Check grub config

- name: Install cpuwer tools 
  ansible.builtin.package: 
    name: linux-tools-generic
    state: present

- name: Check if cpu supports governor
  stat: 
    path: /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
  register: file_status
  
- name: Check supported cpufreq governors
  shell: grep {{ cpu_governor }} /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
  register: scaling_governors
  when: file_status.stat.exists

- name: Set cpu governor #1
  ansible.builtin.command: > 
    cpupower frequency-set -g {{ cpu_governor}}
  register: governor
  when: scaling_governors is changed
  failed_when: governor != 0
  ignore_errors: true

- name: Set cpu to governor #2
  ansible.builtin.shell: >
    echo performance | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  ignore_errors: true

- name: Check current cpu governor
  ansible.builtin.shell: > 
    cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | uniq | grep {{ cpu_governor}}
  register: cpu_governor_true
  failed_when: cpu_governor_true == 0 