
- name: Display Host information
  debug:
    msg:
      - "------- CPU Info -------------"
      - "Host has processor: {{ hostvars[inventory_hostname].ansible_processor }}"
      - "with total cores: {{ hostvars[inventory_hostname].ansible_processor_cores }}"
      - "with threads per core: {{ hostvars[inventory_hostname].ansible_processor_threads_per_core }}"
      - "cpu governor: {{ common_cpu_governor_true.stdout}}"
      - "------- Kernel Info -------------"
      - "The current cmdline: {{ lookup('ansible.builtin.file', '/proc/cmdline') }}"
      - "------- Network Info -------------"
      - "Inteface: {{ common_new_iface_name}} 
      -  alias {{ hostvars[inventory_hostname].ansible_default_ipv4.alias }}" 
      - "IP: {{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
      - "NETMASK: {{ hostvars[inventory_hostname].ansible_default_ipv4.netmask}}"
      - "MAC: {{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress}}"
      - "------- Encrypted Disk Info -------------"
      - "{{ luks_partitions.stdout}}"

# - name: Print all available facts
#   ansible.builtin.debug:
#     var: ansible_facts