- name: Include tasks to common role
  ansible.builtin.include_tasks:
    file: set_cpu.yml

- name: Include tasks to common role
  ansible.builtin.include_tasks:
    file: rename_interface.yml

- name: Include tasks to common role
  ansible.builtin.include_tasks:
    file: display_info.yml
