# common/tasks/rename_interface.yml

- name: Rename interface with systemd
  ansible.builtin.template:
    src: "dev-link.j2"
    dest: "/etc/systemd/network/10-eth.link"

- name: Rename interface in netplan
  replace:
    path: /etc/netplan/50-cloud-init.yaml
    regexp: "{{ common_iface_name}}"
    replace: " {{ common_new_iface_name}}"
  register: netplan_config  

- name: Apply Netplan
  ansible.builtin.command: netplan apply
  register: apply_netplan
  failed_when: apply_netplan.rc != 0
  when: netplan_config.changed

- name: Install packages
  ansible.builtin.package:
    name: iproute2
    state: present

- name: Update udev rules config
  template:
    src: udev-net-rule.j2
    dest: "/etc/udev/rules.d/70-persistent-net.rules"
  notify:
    - Reload udev

- name: Rename network interface
  ansible.builtin.shell: |
    ip link set dev {{ common_iface_name }} down && ip link set dev {{ common_iface_name }} name {{ common_new_iface_name }} && ip link set dev {{ common_new_iface_name }} up && networkctl renew {{ common_new_iface_name}}
  args:
    creates: /sys/class/net/{{ common_new_iface_name }}
    removes: /sys/class/net/{{ common_iface_name }}
  register: interface_rename_result
